services:
  - type: web
    name: vn-realestate-ml-api
    runtime: python
    buildCommand: pip install -r requirements_ml.txt
    startCommand: uvicorn ml_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

